### PR TITLE
chore(CI): fix checks

### LINKED ISSUE #18: Fix CI checks

### PR DESCRIPTION
**Pull request by mapra99**
Closes #18 

Changelog:
- Enabled the publish workflow, but only to be triggered on release
- Removed FUNDING.yml and config.yml files, not sure what they do but looks like we don't need them for now
- Removed `<App />` test and added a new simple test for the `<Home />` page.
- Configure action files to run only on pushes to avoid running twice on PRs
- Split test action file into multiple files/workflows to have each check run simultaneously
- Changed the TS config to avoid doing checks on node_module files
- Updated `jest` and `ts-jest` libraries to their latest versions
- Attended some errors that eslint was yelling on some files

Here is a summary of the CI checks we are doing on each PR:
- We package the app (that is, generate the installer/executable) for macOS, windows and ubuntu
- We run jest tests
- We run eslint and typescript checks
- We run CodeQL analysis to detect security issues

### CODE REVIEW

**Review by ImMPrada — COMMENTED** [review]
.erb/configs/webpack.config.renderer.dev.ts

a warning:
image

**Review by ImMPrada — COMMENTED** [review]
I saw this case:

 having a file src/renderer/components/atoms/index.ts, containing:
```
export {default as Text} from './Text';
```

lint says 'prefer default export'

is something we can set up here? or is a mistake o'mine

**Comment by mapra99** [comment]
> .erb/configs/webpack.config.renderer.dev.ts

Yeah that complain,  I didn't understand it very well, not sure what this `code!` piece does, so I'm not sure how to fix it hahah, and since this is webpack config it's a bit hard to debug. It's a warning anyways, I think we can leave it as is, we won't touch that file too often

**Comment by mapra99** [comment]
> lint says 'prefer default export'

it means that, instead of having a normal export, which is what you have, you should use a default export, like this:
```javascript
export default from './Text';
```

However that `src/renderer/components/atoms/index.ts` file is meant to export all the atom components, so I think it's ok to avoid default exports in those "lists index" files, we can ignore the rule manually by adding this `/* eslint-disable import/prefer-default-export */` on the first line.

For files that are specifically focused on exporting a component, function, etc, I do think we should use default exports, so that's why we have that rule


Also to keep things simple I'm thinking about either not using these `index` files at all, or disabling the eslint rule. What do you think?

**Review by ImMPrada — APPROVED** [review]
So as we discussed, let's disable the check at each index of atomic design groups

cool cool cool!

**Pull request merged**
